// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Ensure DATABASE_URL is set at build/runtime. Throw early if missing so TypeScript
    // receives a `string` value and the runtime fails loudly instead of producing
    // an ambiguous configuration.
    url: (() => {
      const url = process.env["DATABASE_URL"];
      if (!url) throw new Error("Environment variable DATABASE_URL is not set");
      return url;
    })(),
  },
});
